### ISSUE TITLE
Drop a token on testnet to users when they create a new to-do item

### ISSUE THREAD

**Issue by cupOJoseph** [UseKeyp/usekeyp-example-app-express#6]
dependent on #7 

- [ ] Use keyp API to send a token on mumbai or sepolia when a new todo was been created
- [ ] make it clear some blockchain thing has happened by showing the tx hash, or link to etherscan in a new section above User Details called `Transaction History`

- [ ] Add docs to the readme for the user to copy their `API Access Token` 
- [ ] add "What to try next" section on the website AND docs: 

```markdown
#What to do next
You have logged in and now have a wallet. You can also create buttons to login with twitter, google, chess.com, etc.. Try sending tokens to the created addresses or using the Keyp API for other interactions.
```

Goal: make it clear that user can easy be airdropped things once they are logged in.
